Angelez/bibentries
allenai/mmda pull request #113
Opened 2022-07-29 22:16 UTC by geli-gel

Draft PR - looking for help with understanding how tokens are passed into the Document and how I get the tokens from within the model's returned bounding box

2022-07-29 22:25 UTC, geli-gel commented on mmda/predictors/d2_predictors/bibentry_detection_predictor.py
> +                        end=,
@cmwilhelm This is question #1

2022-07-29 22:30 UTC, geli-gel commented on mmda/predictors/d2_predictors/bibentry_detection_predictor.py
> +                self.postprocess(model_outputs, document.tokens[image_index], image_index, image)
@cmwilhelm This is question #2 - how do I learn more about how tokens exist in the Document that will be given as input? I'm assuming I can make it a requirement that the Document / Instance input contains Tokens per page somehow, but I'm struggling to understand how to match those tokens to what my bounding boxes contain. In my other code I use layoutparser's Layout.filter_by: `bib_tokens = page_tokens.filter_by(bib_block, center=True)`

2022-08-23 18:26 UTC, cmwilhelm requested changes
TIMO interface looks good to me. I'll defer to @kyleclo on the particulars of the mmda predictor since there's a fair amount of logic on using the vila info heuristically.

Just a couple requested changes:

1. Let's give `original_boxes` a more specific name since it's at the top-level document namespace.
2. We probably shouldn't depend on `vila_predictors` for your model. From what I can tell that's just there to allow the integration test to process the PDF before handing to your new predictor. I think we want to do that offline and generate a fixture JSON file instead.

2022-08-23 21:40 UTC, geli-gel commented on ai2_internal/config.yaml
> +    extras_require: [ "bibentry_detection_predictor", "vila_predictors" ]
yes you're right - I'll change the test as you suggested!

2022-08-23 21:41 UTC, geli-gel commented on ai2_internal/config.yaml
> +    cuda: false
whoops

2022-08-23 21:42 UTC, geli-gel commented on ai2_internal/bibentries_v1/integration_test.py
> +"""
yep, that's how it got here, my bad!

2022-08-23 21:44 UTC, geli-gel commented
Going to do some changes to the output Prediction after the sync today - s2airs doesn't need the text stored here anymore, so just going to save boxes only. (output will be bib_entries: List[BoxGroup] and original_boxes: List[BoxGroup]

2022-08-23 22:09 UTC, geli-gel commented on ai2_internal/bibentry_detection_predictor/integration_test.py
> +        for bib_entry in predictions[0].bib_entries:
I thought about making it more specific and decided against it but I think at least checking that the number of bib_entries and raw_bib_entry_boxes is the same would be a good addition

2022-08-24 20:24 UTC, cmwilhelm approved these changes
Thanks for the back and forth Angele. LGTM to merge after the merge conflict is resolved.

2022-08-24 21:02 UTC, merged