Egork/figure table predictors
allenai/mmda pull request #151
Opened 2022-10-04 00:40 UTC by comorado

2022-10-04 04:54 UTC, soldni commented
Quickly changed CI tests config so that `test_figure_table_predictors.py` runs alongside the other tests requiring VILA. PR looks good to me otherwise!

2022-10-05 21:54 UTC, soldni commented
Hey @comorado , some tests seem to be failing after recent commits?

2022-10-05 22:03 UTC, cmwilhelm requested changes
Most of my comments are related to taking a dependency on vila and layout parser directly in your predictor.

All the other predictors assume their upstream dependencies have already been run, and that they are just operating over their outputs. So your predictor shouldn't need to instantiate Vila and LayoutParser itself.

Likewise, we shouldn't encode that dependency in the timo config -- it adds a huge bloat for a model that is just doing some analysis on top of provided span groups.

2022-10-05 22:17 UTC, comorado commented
@soldni Thank you, yes it seems that it is because of this [change](https://github.com/allenai/mmda/pull/150/files) see my comment.

2022-10-05 23:09 UTC, comorado commented on ai2_internal/config.yaml
> +    extras_require: ["dev", "vila_predictors"]
Yes that is correct, thank you for pointing this out.

2022-10-05 23:10 UTC, comorado commented on ai2_internal/config.yaml
> +    artifacts_s3_path: s3://ai2-timo-registry/model-artifacts/vila/ivila-row-layoutlm-finetuned-s2vl-v2.tar.gz
That is right

2022-10-05 23:11 UTC, comorado commented on mmda/predictors/heuristic_predictors/figure_table_predictors.py
> +    REQUIRED_BACKENDS = ['layoutparser', 'vila']
Correct, will take this dependencies down.

2022-10-05 23:57 UTC, comorado commented on mmda/predictors/heuristic_predictors/figure_table_predictors.py
> +        predictions.extend(self._predict(document, caption_type='Table'))
@cmwilhelm I need a single list, each of _predict returns a list so probably
`list(zip(self._predict(document, caption_type="Figure"), self._predict(document, caption_type="Table")))`

2022-10-06 00:13 UTC, comorado commented on mmda/predictors/heuristic_predictors/figure_table_predictors.py
> +    REQUIRED_DOCUMENT_FIELDS = ['layoutparser_span_groups', 'vila_span_groups']
Images is not part of the fields for some reason. We do not add it to the [self._fields](https://github.com/allenai/mmda/blob/main/mmda/types/document.py#L102-L122)

2022-10-06 00:16 UTC, comorado commented on ai2_internal/figure_table_predictors/interface.py
> +    table_figure_caption_list: List[api.SpanGroup]
Hmm I see so you proposing to return a tuple we can definitely do that!

2022-10-06 23:22 UTC, comorado commented on setup.py
> +        "scipy",
@cmwilhelm I've tried to move scipy into `extra_requires` section but getting an error
`/usr/local/lib/python3.8/site-packages/mmda/predictors/heuristic_predictors/figure_table_predictors.py:5: in <module>
    from scipy.optimize import linear_sum_assignment
E   ModuleNotFoundError: No module named 'scipy'
`

Here is the lists I added
`"figure_table_predictors": ["scipy"],`

2022-10-11 20:06 UTC, cmwilhelm commented on ai2_internal/figure_table_predictors/interface.py
> +    table_caption_list: List[api.SpanGroup]
```python
table_list: List[api.SpanGroup]
figure_list: List[api.SpanGroup]
```

?

2022-10-11 20:06 UTC, cmwilhelm approved these changes
LGTM except one small question on the output `Instance`. Looks like the field names might be off?

Thanks for the extra round of attention here.

2022-10-11 20:07 UTC, merged